/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: macshares.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "macshares.pb-c.h"
void   secret_share__init
                     (SecretShare         *message)
{
  static const SecretShare init_value = SECRET_SHARE__INIT;
  *message = init_value;
}
size_t secret_share__get_packed_size
                     (const SecretShare *message)
{
  assert(message->base.descriptor == &secret_share__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t secret_share__pack
                     (const SecretShare *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &secret_share__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t secret_share__pack_to_buffer
                     (const SecretShare *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &secret_share__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SecretShare *
       secret_share__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SecretShare *)
     protobuf_c_message_unpack (&secret_share__descriptor,
                                allocator, len, data);
}
void   secret_share__free_unpacked
                     (SecretShare *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &secret_share__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor secret_share__field_descriptors[2] =
{
  {
    "mackeyshare_2",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SecretShare, mackeyshare_2),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mackeyshare_p",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SecretShare, mackeyshare_p),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned secret_share__field_indices_by_name[] = {
  0,   /* field[0] = mackeyshare_2 */
  1,   /* field[1] = mackeyshare_p */
};
static const ProtobufCIntRange secret_share__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor secret_share__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "secret_share",
  "SecretShare",
  "SecretShare",
  "",
  sizeof(SecretShare),
  2,
  secret_share__field_descriptors,
  secret_share__field_indices_by_name,
  1,  secret_share__number_ranges,
  (ProtobufCMessageInit) secret_share__init,
  NULL,NULL,NULL    /* reserved[123] */
};
