/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: macshares.proto */

#ifndef PROTOBUF_C_macshares_2eproto__INCLUDED
#define PROTOBUF_C_macshares_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _SecretShare SecretShare;


/* --- enums --- */


/* --- messages --- */

/*
 * Message representing MAC shares
 */
struct  _SecretShare
{
  ProtobufCMessage base;
  /*
   * MAC key share 2
   */
  char *mackeyshare_2;
  /*
   * MAC key share P         
   */
  char *mackeyshare_p;
};
#define SECRET_SHARE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&secret_share__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/* SecretShare methods */
void   secret_share__init
                     (SecretShare         *message);
size_t secret_share__get_packed_size
                     (const SecretShare   *message);
size_t secret_share__pack
                     (const SecretShare   *message,
                      uint8_t             *out);
size_t secret_share__pack_to_buffer
                     (const SecretShare   *message,
                      ProtobufCBuffer     *buffer);
SecretShare *
       secret_share__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   secret_share__free_unpacked
                     (SecretShare *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*SecretShare_Closure)
                 (const SecretShare *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor secret_share__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_macshares_2eproto__INCLUDED */
