/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: secretsharing.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "secretsharing.pb-c.h"
void   player_info__init
                     (PlayerInfo         *message)
{
  static const PlayerInfo init_value = PLAYER_INFO__INIT;
  *message = init_value;
}
size_t player_info__get_packed_size
                     (const PlayerInfo *message)
{
  assert(message->base.descriptor == &player_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t player_info__pack
                     (const PlayerInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &player_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t player_info__pack_to_buffer
                     (const PlayerInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &player_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PlayerInfo *
       player_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PlayerInfo *)
     protobuf_c_message_unpack (&player_info__descriptor,
                                allocator, len, data);
}
void   player_info__free_unpacked
                     (PlayerInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &player_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   mac_share__init
                     (MacShare         *message)
{
  static const MacShare init_value = MAC_SHARE__INIT;
  *message = init_value;
}
size_t mac_share__get_packed_size
                     (const MacShare *message)
{
  assert(message->base.descriptor == &mac_share__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mac_share__pack
                     (const MacShare *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mac_share__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mac_share__pack_to_buffer
                     (const MacShare *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mac_share__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MacShare *
       mac_share__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MacShare *)
     protobuf_c_message_unpack (&mac_share__descriptor,
                                allocator, len, data);
}
void   mac_share__free_unpacked
                     (MacShare *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mac_share__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor player_info__field_descriptors[2] =
{
  {
    "kii_job_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(PlayerInfo, kii_job_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "player_number",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(PlayerInfo, player_number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned player_info__field_indices_by_name[] = {
  0,   /* field[0] = kii_job_id */
  1,   /* field[1] = player_number */
};
static const ProtobufCIntRange player_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor player_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PlayerInfo",
  "PlayerInfo",
  "PlayerInfo",
  "",
  sizeof(PlayerInfo),
  2,
  player_info__field_descriptors,
  player_info__field_indices_by_name,
  1,  player_info__number_ranges,
  (ProtobufCMessageInit) player_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor mac_share__field_descriptors[3] =
{
  {
    "mackeyshare_2",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MacShare, mackeyshare_2),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mackeyshare_p",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MacShare, mackeyshare_p),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "seeds",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MacShare, seeds),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mac_share__field_indices_by_name[] = {
  0,   /* field[0] = mackeyshare_2 */
  1,   /* field[1] = mackeyshare_p */
  2,   /* field[2] = seeds */
};
static const ProtobufCIntRange mac_share__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor mac_share__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MacShare",
  "MacShare",
  "MacShare",
  "",
  sizeof(MacShare),
  3,
  mac_share__field_descriptors,
  mac_share__field_indices_by_name,
  1,  mac_share__number_ranges,
  (ProtobufCMessageInit) mac_share__init,
  NULL,NULL,NULL    /* reserved[123] */
};
