/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: secretsharing.proto */

#ifndef PROTOBUF_C_secretsharing_2eproto__INCLUDED
#define PROTOBUF_C_secretsharing_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _PlayerInfo PlayerInfo;
typedef struct _MacShare MacShare;


/* --- enums --- */


/* --- messages --- */

/*
 * Message representing player information
 */
struct  _PlayerInfo
{
  ProtobufCMessage base;
  /*
   * Job ID associated with the player
   */
  int32_t kii_job_id;
  /*
   * Unique player number
   */
  int32_t player_number;
};
#define PLAYER_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&player_info__descriptor) \
    , 0, 0 }


/*
 * Message representing MAC shares
 */
struct  _MacShare
{
  ProtobufCMessage base;
  /*
   * MAC key share 2
   */
  char *mackeyshare_2;
  /*
   * MAC key share P
   */
  char *mackeyshare_p;
  /*
   * Seeds used for the shares
   */
  char *seeds;
};
#define MAC_SHARE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&mac_share__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/* PlayerInfo methods */
void   player_info__init
                     (PlayerInfo         *message);
size_t player_info__get_packed_size
                     (const PlayerInfo   *message);
size_t player_info__pack
                     (const PlayerInfo   *message,
                      uint8_t             *out);
size_t player_info__pack_to_buffer
                     (const PlayerInfo   *message,
                      ProtobufCBuffer     *buffer);
PlayerInfo *
       player_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   player_info__free_unpacked
                     (PlayerInfo *message,
                      ProtobufCAllocator *allocator);
/* MacShare methods */
void   mac_share__init
                     (MacShare         *message);
size_t mac_share__get_packed_size
                     (const MacShare   *message);
size_t mac_share__pack
                     (const MacShare   *message,
                      uint8_t             *out);
size_t mac_share__pack_to_buffer
                     (const MacShare   *message,
                      ProtobufCBuffer     *buffer);
MacShare *
       mac_share__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   mac_share__free_unpacked
                     (MacShare *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*PlayerInfo_Closure)
                 (const PlayerInfo *message,
                  void *closure_data);
typedef void (*MacShare_Closure)
                 (const MacShare *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor player_info__descriptor;
extern const ProtobufCMessageDescriptor mac_share__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_secretsharing_2eproto__INCLUDED */
